---
# VulnGuard AI - Rollback Playbook
# pb-rollback
#
# Restores system to pre-change state using VulnGuard backups
# EMERGENCY USE ONLY
#
# This playbook is called automatically when remediation fails
# or can be invoked manually for emergency rollback

- name: VulnGuard Emergency Rollback
  hosts: "{{ target_hosts | default('all') }}"
  become: yes
  gather_facts: yes

  vars:
    # Backup directory
    backup_dir: "/var/backups/vulnguard"

    # Rollback tracking
    vulnerability_id: "{{ vuln_id | default('UNKNOWN') }}"
    execution_id: "{{ exec_id | default('UNKNOWN') }}"

    # Specific backup timestamp to restore (optional)
    # If not specified, uses most recent backup
    restore_timestamp: "{{ timestamp | default('') }}"

  pre_tasks:
    - name: Record rollback initiation
      shell: |
        echo "=== VulnGuard ROLLBACK INITIATED ===" > {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
        echo "Vulnerability ID: {{ vulnerability_id }}" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
        echo "Execution ID: {{ execution_id }}" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
        echo "Timestamp: {{ ansible_date_time.iso8601 }}" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
        echo "Initiated by: VulnGuard Remediation Agent" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
      changed_when: false

    - name: Find available backups
      find:
        paths: "{{ backup_dir }}"
        patterns: "*.bak"
        file_type: file
      register: backup_files

    - name: Display available backups
      debug:
        msg: "Found {{ backup_files.files | length }} backup files"

  tasks:
    # =========================================================================
    # NGINX ROLLBACK
    # =========================================================================
    - name: Find nginx backup
      find:
        paths: "{{ backup_dir }}"
        patterns: "nginx*.bak"
        file_type: file
      register: nginx_backups

    - name: Restore nginx configuration
      copy:
        src: "{{ (nginx_backups.files | sort(attribute='mtime', reverse=true) | first).path }}"
        dest: /etc/nginx/nginx.conf
        remote_src: yes
        backup: yes
      when: nginx_backups.files | length > 0
      notify: Restart nginx

    # =========================================================================
    # APACHE ROLLBACK
    # =========================================================================
    - name: Find Apache SSL backup
      find:
        paths: "{{ backup_dir }}"
        patterns: "apache-ssl*.bak"
        file_type: file
      register: apache_backups

    - name: Restore Apache SSL configuration
      copy:
        src: "{{ (apache_backups.files | sort(attribute='mtime', reverse=true) | first).path }}"
        dest: /etc/apache2/mods-available/ssl.conf
        remote_src: yes
        backup: yes
      when: apache_backups.files | length > 0
      notify: Restart Apache

    # =========================================================================
    # SSH ROLLBACK
    # =========================================================================
    - name: Find SSH backup
      find:
        paths: "{{ backup_dir }}"
        patterns: "sshd_config*.bak"
        file_type: file
      register: ssh_backups

    - name: Restore SSH configuration
      copy:
        src: "{{ (ssh_backups.files | sort(attribute='mtime', reverse=true) | first).path }}"
        dest: /etc/ssh/sshd_config
        remote_src: yes
        backup: yes
        validate: '/usr/sbin/sshd -t -f %s'
      when: ssh_backups.files | length > 0
      notify: Reload SSH

    # =========================================================================
    # OPENSSL ROLLBACK
    # =========================================================================
    - name: Find OpenSSL backup
      find:
        paths: "{{ backup_dir }}"
        patterns: "openssl*.bak"
        file_type: file
      register: openssl_backups

    - name: Restore OpenSSL configuration
      copy:
        src: "{{ (openssl_backups.files | sort(attribute='mtime', reverse=true) | first).path }}"
        dest: /etc/ssl/openssl.cnf
        remote_src: yes
        backup: yes
      when: openssl_backups.files | length > 0

    # =========================================================================
    # MODULI ROLLBACK
    # =========================================================================
    - name: Find SSH moduli backup
      find:
        paths: "{{ backup_dir }}"
        patterns: "moduli*.bak"
        file_type: file
      register: moduli_backups

    - name: Restore SSH moduli
      copy:
        src: "{{ (moduli_backups.files | sort(attribute='mtime', reverse=true) | first).path }}"
        dest: /etc/ssh/moduli
        remote_src: yes
        backup: yes
      when: moduli_backups.files | length > 0

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Reload SSH
      service:
        name: sshd
        state: reloaded

  post_tasks:
    - name: Verify services are running
      service_facts:

    - name: Check nginx status
      debug:
        msg: "nginx status: {{ ansible_facts.services['nginx.service'].state | default('not installed') }}"
      when: "'nginx.service' in ansible_facts.services"

    - name: Check Apache status
      debug:
        msg: "Apache status: {{ ansible_facts.services['apache2.service'].state | default('not installed') }}"
      when: "'apache2.service' in ansible_facts.services"

    - name: Check SSH status
      debug:
        msg: "SSH status: {{ ansible_facts.services['sshd.service'].state | default(ansible_facts.services['ssh.service'].state | default('not installed')) }}"

    - name: Record rollback completion
      shell: |
        echo "=== ROLLBACK COMPLETED ===" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
        echo "Completion time: {{ ansible_date_time.iso8601 }}" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
        echo "" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
        echo "Services restored:" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log
        systemctl list-units --type=service --state=running | grep -E "(nginx|apache|sshd)" >> {{ backup_dir }}/rollback_{{ ansible_date_time.epoch }}.log || true
      changed_when: false

    - name: Display rollback summary
      debug:
        msg: |
          ========================================
          VULNGUARD ROLLBACK COMPLETED
          ========================================
          Vulnerability ID: {{ vulnerability_id }}
          Execution ID: {{ execution_id }}

          Restored configurations:
          - nginx: {{ 'Yes' if nginx_backups.files | length > 0 else 'No backup found' }}
          - Apache: {{ 'Yes' if apache_backups.files | length > 0 else 'No backup found' }}
          - SSH: {{ 'Yes' if ssh_backups.files | length > 0 else 'No backup found' }}
          - OpenSSL: {{ 'Yes' if openssl_backups.files | length > 0 else 'No backup found' }}

          Please verify system functionality manually.
          ========================================
