---
# VulnGuard AI - SSH Hardening Playbook
# pb-ssh-hardening
#
# Removes weak ciphers and enforces secure SSH configuration
# Supports: Linux (OpenSSH)
#
# GUARDRAILS:
# - Creates backup before changes
# - Supports check mode (dry run)
# - Does NOT require restart (uses reload)
# - Validates config before applying

- name: SSH Configuration Hardening
  hosts: "{{ target_hosts | default('all') }}"
  become: yes
  gather_facts: yes

  vars:
    # Backup directory
    backup_dir: "/var/backups/vulnguard"

    # VulnGuard tracking
    vulnerability_id: "{{ vuln_id | default('UNKNOWN') }}"
    approval_id: "{{ approval_id | default('UNKNOWN') }}"

    # SSH hardening settings
    ssh_config:
      # Protocol settings
      Protocol: 2

      # Disable weak algorithms
      Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
      MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
      KexAlgorithms: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256"
      HostKeyAlgorithms: "ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256"

      # Authentication settings
      PermitRootLogin: "prohibit-password"
      PasswordAuthentication: "no"
      PubkeyAuthentication: "yes"
      PermitEmptyPasswords: "no"
      ChallengeResponseAuthentication: "no"

      # Security settings
      X11Forwarding: "no"
      AllowTcpForwarding: "no"
      AllowAgentForwarding: "no"
      MaxAuthTries: 3
      MaxSessions: 2
      LoginGraceTime: 60
      ClientAliveInterval: 300
      ClientAliveCountMax: 2

      # Logging
      LogLevel: "VERBOSE"
      SyslogFacility: "AUTH"

  pre_tasks:
    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0750'

    - name: Backup current SSH configuration
      copy:
        src: /etc/ssh/sshd_config
        dest: "{{ backup_dir }}/sshd_config.{{ ansible_date_time.epoch }}.bak"
        remote_src: yes

    - name: Record pre-change state
      shell: |
        echo "=== VulnGuard SSH Pre-Change State ===" > {{ backup_dir }}/ssh_pre_change_{{ ansible_date_time.epoch }}.log
        echo "Vulnerability ID: {{ vulnerability_id }}" >> {{ backup_dir }}/ssh_pre_change_{{ ansible_date_time.epoch }}.log
        echo "Timestamp: {{ ansible_date_time.iso8601 }}" >> {{ backup_dir }}/ssh_pre_change_{{ ansible_date_time.epoch }}.log
        sshd -T 2>/dev/null | grep -E "^(ciphers|macs|kexalgorithms|hostkeyalgorithms)" >> {{ backup_dir }}/ssh_pre_change_{{ ansible_date_time.epoch }}.log
      changed_when: false

  tasks:
    # =========================================================================
    # APPLY SSH HARDENING
    # =========================================================================
    - name: Apply SSH hardening settings
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?{{ item.key }}"
        line: "{{ item.key }} {{ item.value }}"
        state: present
        backup: yes
        validate: '/usr/sbin/sshd -t -f %s'
      loop: "{{ ssh_config | dict2items }}"
      notify: Reload SSH

    - name: Remove deprecated SSH options if present
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item }}"
        state: absent
        backup: yes
        validate: '/usr/sbin/sshd -t -f %s'
      loop:
        - "^UsePrivilegeSeparation"  # Deprecated in OpenSSH 7.5
        - "^KeyRegenerationInterval"  # Protocol 1 only
        - "^ServerKeyBits"            # Protocol 1 only
        - "^RSAAuthentication"        # Deprecated
        - "^RhostsRSAAuthentication"  # Deprecated

    # =========================================================================
    # MODULI HARDENING (Remove weak DH primes)
    # =========================================================================
    - name: Backup SSH moduli file
      copy:
        src: /etc/ssh/moduli
        dest: "{{ backup_dir }}/moduli.{{ ansible_date_time.epoch }}.bak"
        remote_src: yes
      ignore_errors: yes

    - name: Remove weak DH moduli (< 3072 bits)
      shell: |
        awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe
        mv /etc/ssh/moduli.safe /etc/ssh/moduli
      args:
        creates: "{{ backup_dir }}/moduli_hardened"
      register: moduli_result

    - name: Mark moduli as hardened
      file:
        path: "{{ backup_dir }}/moduli_hardened"
        state: touch
      when: moduli_result.changed

  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded
      when: not ansible_check_mode

  post_tasks:
    - name: Validate SSH configuration
      command: sshd -t
      changed_when: false
      when: not ansible_check_mode

    - name: Verify SSH service is running
      service:
        name: sshd
        state: started
      when: not ansible_check_mode

    - name: Record post-change state
      shell: |
        echo "=== VulnGuard SSH Post-Change State ===" > {{ backup_dir }}/ssh_post_change_{{ ansible_date_time.epoch }}.log
        echo "Timestamp: {{ ansible_date_time.iso8601 }}" >> {{ backup_dir }}/ssh_post_change_{{ ansible_date_time.epoch }}.log
        sshd -T 2>/dev/null | grep -E "^(ciphers|macs|kexalgorithms|hostkeyalgorithms)" >> {{ backup_dir }}/ssh_post_change_{{ ansible_date_time.epoch }}.log
        systemctl status sshd >> {{ backup_dir }}/ssh_post_change_{{ ansible_date_time.epoch }}.log 2>&1
      changed_when: false
      when: not ansible_check_mode

    - name: Display completion message
      debug:
        msg: "SSH hardening completed for vulnerability {{ vulnerability_id }}. Service reloaded (no restart required)."
